name: sindh_truck_cargo_hub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  recaptcha_v3: ^0.2.0
  flutter_dotenv: ^5.0.2
  firebase_core: ^3.4.0
  firebase_messaging: ^15.2.4
  firebase_auth: ^5.2.0
  image_picker: ^1.1.2
  firebase_storage: ^12.2.0
  cloud_firestore: ^5.4.0
  image: ^4.0.17
  file_picker: ^9.0.2
  geolocator: ^13.0.4
  geocoding: ^3.0.0
  googleapis_auth: ^1.4.0
  intl: ^0.19.0
  provider: ^6.1.4
  shared_preferences: ^2.2.2
  flutter_typeahead: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true  # 👈 Add this line


  assets:
    - assets/truck2.png
    - assets/Rectangle 1467.png
    - assets/firebase-admin-key.json
